
@startuml SequenzdiagrammHandlungsschrittAusführen
title Sequenzdiagramm Handlungsschritt ausfuehren

actor Benutzer
participant "SpielView" as G
participant "SpielViewModel" as A
Participant "Uebungszenario" as B
Participant "Information" as H
participant "Aufzeichnung" as C
participant "Handlungsschritt" as D
participant "Operationen" as F


Benutzer -> G: '=' gedrueckt
activate G

G->A:HandlungsschrittAusfuehren(\noperation1, operation2, operatonsTyp)
activate A

A-> B: HandlungsschrittAusfuehrenLassen(\nOperand1, Operand2, OperationsTyp)
activate B

B -> D: ErzeugeHandlungsschritt(\nRolle, Operand1, Operand2, OperationsTyp)
activate D

D -> F: Fuehre Operation durch
activate F

F->D: set:Ergebnis(Information)
deactivate F

D -> B: get:Ergebnis(Information)
deactivate D

B -> C: HaengeHandlungsschrittAn(\nHandlungsschritt handlungsschritt)
activate C

C->B:
deactivate C

B->A: Information Ergebnis
deactivate B

A -> G: Information Ergebnis
deactivate A

@enduml
