# pipeline quakrypto
image: microsoft/dotnet:latest
stages:
  - build
  - test
  - deploy

before_script:
  - "cd 03_Implementierung"
  - "dotnet restore"

build:
  stage: build
  script:
    - "dotnet build --output output"
    
test:
  stage: test
  script:
  - "dotnet test"
  dependencies:
  - build

deploy:
  stage: deploy
  script:
  - "dotnet build --configuration Release --output output"
  artifacts:
    name: "Release"
    paths:
      - 03_Implementierung/output/*
  dependencies:
  - build
  - test