variables:
  MSBUILD_PATH: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe'
  NUNIT_PATH: 'C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe'

stages:
  - build
  - test

build_job:
  stage: build
  script:
    - echo "Test"
    - '& "$env:MSBUILD_PATH" "03_Implementierung\quakrypto\quakrypto.sln"'
    - echo "Test"

test_job:
  stage: test
  script:
    - echo "Test"
    - echo pwd
    # - '& "$env:NUNIT_PATH" "03_Implementierung\quakrypto\TestLibrary\obj\Debug\TestLibary.dll'
    - echo "Test"
