@startuml Klassen_Modell_old_style

skinparam pageMargin 10
skinparam pageExternalColor gray
skinparam pageBorderColor black

/'************************************************************'/
/'PACKAGE Model												  '/
/'************************************************************'/
package Model
{
	together {
		interface IUebungsszenario <<interface>>
		{
			+ <<get>> Rollen(): List<Rolle> 
			+ <<get>> Schwierigkeitsgrad(): SchwierigkeitsgradEnum 
			+ <<get>> Variante(): IVariante 
			+ <<get>> StartPhase(): uint
			+ <<get>> EndPhase(): uint 
			+ <<get>> Uebertragungskanal(): Uebertragungskanal 
			+ <<get>> Aufzeichnung(): Aufzeichnung 
			+ <<get>> Name(): string 
			+ RolleHinzufuegen(rolle: Rolle): bool
			+ GebeRolleFrei(rolle: RolleEnum)
			+ Starten()
			+ NaechsterZug(): bool
			+ GebeBildschrimFrei(passwort: string): bool 
			+ HandlungsschrittAusfuehrenLassen(handlungsschritt: Handlungsschritt): Information
			+ SpeichereInformationenAb(informationID: uint)
			+ LoescheInformatione(informationID: uint)
			+ Beenden()
		}

		class UebungsszenarioLokal implements IUebungsszenario
		{
			+ UebungsszenarioLokal(schwierigkeitsgrad: SchwierigkeitsgradEnum, variante: IVariante, startPhase: uint, endPhase: uint) <<create>>
			+ RolleHinzufuegen(rolle: Rolle): bool
			+ GebeRolleFrei(rolle: RolleEnum)
			+ Starten()
			+ NaechsterZug(): bool
			+ GebeBildschrimFrei(passwort: string): bool 
			+ HandlungsschrittAusfuehrenLassen(handlungsschritt: Handlungsschritt): Information
			+ SpeichereInformationenAb(informationID: uint)
			+ LoescheInformatione(informationID: uint)
			+ Beenden()
		}

		class UebungsszenarioNetzwerk implements IUebungsszenario
		{
			+ UebungsszenarioNetzwerk(schwierigkeitsgrad: SchwierigkeitsgradEnum, variante: IVariante, startPhase: uint, endPhase: uint) <<create>>
			+ RolleHinzufuegen(rolle: Rolle): bool
			+ GebeRolleFrei(rolle: RolleEnum)
			+ Starten()
			+ NaechsterZug(): bool
			+ GebeBildschrimFrei(passwort: string): bool 
			+ HandlungsschrittAusfuehrenLassen(handlungsschritt: Handlungsschritt): Information
			+ SpeichereInformationenAb(informationID: uint)
			+ LoescheInformatione(informationID: uint)
			+ Beenden()
			+ ZugWurdeBeendet(handlungsschritte: List<Handlungsschritt>)
			+ UebungsszenarioWurdeBeendetHost()
			+ UebungsszenarioWurdeBeendetClient()
			+ AufzeichnungUpdate(handlungsschritte: List<Handlungsschritt>)
			+ KontrolleErhalten()
			+ UebungsszenarioWurdeGestartet()
			+ NeueRollenInformation(rolleAlice: Rolle, rolleBob: Rolle?, rolleEve: Rolle?)
		}
	}

	together {
		class Aufzeichnung
		{
			+ <<get>> Handlungsschritte(): List<Handlungsschritt>
			+ Aufzeichnung() <<create>>
			+ HaengeHandlungsschrittAn(Handlungsschritt: Handlungsschritt)
			+ HaengeListeHandlungsschritteAn(Handlungsschritte: List<Handlungsschritt>)
		}

		class Uebertragungskanal
		{
			+ <<get>> photonenKanal(): List<Information> 
			+ <<get>> bitKanal(): List<Information>
			+ Uebertragungskanal() <<create>>
			+ SpeicherNachrichtAb(informartion: Information)
			+ LeseKanalAus(kanal: KanalEnum): List<Information>
			+ LoescheNachricht(kanal: KanalEnum, informationID: uint)
		}

		enum KanalEnum
		{
			PhotonenKanal
			BitKanal
		}

		enum SchwierigkeitsgradEnum
		{
			Leicht
			Mittel
			Schwer
		}
	}
	
	together {
		class Operationen
		{
			+ NachrichtSenden() : Information
			+ NachrichtEmpfangen() : Information 
			+ NachrichtAbhoeren() : Information 
			+ BitfolgeGenerierenZahl() : Information 
			+ BitfolgeGenerierenAngabe() : Information 
			+ PolarisationsschemataGenerierenZahl() : Information 
			+ PolarisationsschemataGenerierenAngabe() : Information 
			+ PhotonenGenerieren() : Information 
			+ BitmaskeGenerieren() : Information 
			+ PolschataVergleichen() : Information 
			+ BitfolgenVergleichen() : Information 
			+ PhotonenZuBitfolge() : Information 
			+ TextVerschluesseln() : Information 
			+ TextEntschluesseln() : Information 
			+ BitsStreichen() : Information 
			+ BitsFreiBearbeiten() : Information 
			+ ZugBeenden() : bool 
		}

		enum OperationsEnum
		{
			NachrichtSenden
			NachrichtEmpfangen
			NachrichtAbhoeren
			BitfolgeGenerierenZahl
			BitfolgeGenerierenAngabe
			PolarisationsschemataGenerierenZahl
			PolarisationsschemataGenerierenAngabe
			PhotonenGenerieren
			BitmaskeGenerieren
			PolschataVergleichen
			BitfolgenVergleichen
			PhotonenZuBitfolge
			TextGenerieren
			TextVerschluesseln
			TextEntschluesseln
			BitsStreichen
			BitsFreiBearbeiten
			TexGenerieren
			ZahlGenerieren
			ZugBeenden
		}
	}

	together {
		class Information
		{
			+ <<get>> Information(informationID: uint, informartionsName: string, informartionsTyp: InformationsEnum, informartionsEmpfaenger: RolleEnum, informartionsInhalt: object) <<create>>
			+ <<get>> InformationsID(): uint
			+ <<get>> InformationsName(): string
			+ <<get>> InformationsTyp(): InformationsEnum
			+ <<get>> InformationsEmpfaenger(): RolleEnum
			+ <<get>> InformationsInhalt(): object
		}

		class Handlungsschritt
		{
			- {static} op : Operationen
			- {static} HandlungsschrittKommando : Dictionary<OperationsEnum, Delegate>
			+ Handlungsschritt(informationsID: uint, operationsTyp: OperationsEnum, operand1: Information, operand2: Information, ergebnisName: String, rolle: RolleEnum) <<create>>
			+ <<get>> OperationsTyp(): OperationsEnum
			+ <<get>> Operand1(): Information
			+ <<get>> Operand2(): Information
			+ Ergebnis: Information
			+ ErgebnisName: string
			+ <<get>> Rolle(): RolleEnum
			+ <<get, set>> AktuellePhase(): uint
			+ HandlungsschrittAusfuehren()
		}

		class Rolle
		{
			+ Rolle(rolle: RolleEnum, alias: string, passwort: string) <<create>>
			+ <<get>> RolleTyp(): Rolle
			+ BeginneZug(passwort: string): bool
			+ ErzeugeHandlungsschritt(operationsTyp: OperationsEnum, operand1: Information, operand2: Information, ergebnisInformationsName: String, rolle: RolleEnum): Handlungsschritt
			+ SpeichereInformationenAb(informartion: Information)
			+ LoescheInformatione(information: Information)
			+ AktualisiereInformationsZaehler(informartionszaehler: uint)
		}

		enum InformationsEnum
		{
			Zahl
			Bitfolge
			Photonen
			Polarisationsschemata
			unscharfePhotonen
			ASCII-Text
			VerschluesselterText
		}

		enum RolleEnum
		{
			Alice
			Bob
			Eve
		}
	}

	together {

		class NetzwerkClient {
			+ <<get>> {static} VerfuegbareLobbys(): ObservableCollection<Lobby>
			+ {static} BeginneSucheNachLobbys()
			+ {static} BeendeSucheNachLobbys()
			+ {static} VerbindeMitUebungsszenario(netzwerkBeitrittInfo: UebungsszenarioNetzwerkBeitritt)
			+ {static} WaehleRolle(gewählteRolle: RolleEnum, alias: string)
			+ {static} GebeRolleFrei(freizugebendeRolle: RolleEnum)
			+ {static} BeendeZug(handlundsschritte: List<Handlungsschritt>)
			+ {static} BeendeUebungsszenario()
			+ {static} Uebungsszenario: UebungsszenarioNetzwerk
		}

		class NetzwerkHost {
			+ <<get>> {static} AliceRolle(): Rolle
			+ <<get>> {static} BobRolle(): Rolle
			+ <<get>> {static} EveRolle(): Rolle
			+ {static} BeendeTCPLobby()
			+ {static} SendeRollenInformation()
			+ {static} StarteUebungsszenario()
			+ {static} UebergebeKontrolle(nächsteRolle: Rolle)
			+ {static} SendeAufzeichnungsUpdate(empfänger: Rolle, neueHandlungsschritte: List<Handlungsschritt>)
			+ {static} BeginneZyklischesSendenVonLobbyinformation(netzwerkBeitrittInfo: UebungsszenarioNetzwerkBeitritt)
			+ {static} BeendeUebungsszenario()
			+ {static} Uebungsszenario: UebungsszenarioNetzwerk
		}

		class UebungsszeanrioNetzwerkBeitrittInfo {
			+ <<get, set>> IPAdress(): IPAddress
			+ <<get, set>> Lobbyname(): string
			+ <<get, set>> Protokoll(): string
			+ <<get, set>> Variante(): string
			+ <<get, set>> Schwierigkeitsgrad(): SchwierigkeitsgradEnum
			+ <<get, set>> AliceIcon(): BitmapImage
			+ <<get, set>> BobIcon(): BitmapImage
			+ <<get, set>> EveIcon(): BitmapImage
			+ UebungsszeanrioNetzwerkBeitrittInfo(address: IPAddress, lobbyname: string, protokoll: string, variante: string, schwierigkeitsgrad: SchwierigkeitsgradEnum, aliceIcon: BitmapImage, bobIcon: BitmapImage, eveIcon: BitmapImage) <<create>>
		}
	}

	together {
		interface IVariante
		{
			+ <<get>> AktuellePhase(): uint
			+ <<get>> AktuelleRolle(): RolleEnum
			+ <<get>> VarianteName(): string
			+ <<get>> ProtokollName(): string
			+ <<get>> MoeglicheRollen(): List<RolleEnum>
			+ NaechsteRolle(): RolleEnum
			+ GebeHilfestellung(schwierigkeitsgrad: SchwierigkeitsgradEnum) : List<OperationsEnum>
			+ erechneAktuellePhase(sender: object, e: NotifyCollectionChangedEventArgs)
		}

		class VarianteNormalerAblauf implements IVariante
		{
			+ VarianteNormalerAblauf(startPhase: uint) <<create>>
			+ NaechsteRolle(): RolleEnum
			+ GebeHilfestellung(schwierigkeitsgrad: SchwierigkeitsgradEnum) : List<OperationsEnum>
			+ BerechneAktuellePhase(sender: object, e: NotifyCollectionChangedEventArgs)
		}

		class VarianteAbhoeren implements IVariante
		{
			+ VarianteAbhoeren(startPhase: uint) <<create>>
			+ NaechsteRolle(): RolleEnum
			+ GebeHilfestellung(schwierigkeitsgrad: SchwierigkeitsgradEnum) : List<OperationsEnum>
			+ BerechneAktuellePhase(sender: object, e: NotifyCollectionChangedEventArgs)
		}

		class VarianteManInTheMiddle implements IVariante
		{
			+ VarianteManInTheMiddle(startPhase: uint) <<create>>
			+ NaechsteRolle(): RolleEnum
			+ GebeHilfestellung(schwierigkeitsgrad: SchwierigkeitsgradEnum) : List<OperationsEnum>
			+ BerechneAktuellePhase(sender: object, e: NotifyCollectionChangedEventArgs)
		}
	}

	together {
		class Wiki
		{
			+ <<get>> {static} WikiSeiten(): ObservableCollection<WikiSeite>
			+ <<get>> {static} WikiIstOffen(): bool
			+ Wiki() <<create>>
			+ SpeichereAlleWikiSeiten()
			+ SeitenErweitern()
			+ SeiteEntfernen()
			+ SeiteSelektieren(identifier: string)
		}

		class WikiSeite {
			+ <<get>> {static} InlineList(): ObservableCollection<Inline>
			+ <<get>> Identifier(): string
			+ WikiSeiteName: string
			+ Inhalt: string
			+ WikiSeite(wikiSeiteName: string, inhalt: string) <<create>>
			+ SetzeAktivStatus(aktiv: bool)
			+ SetzeEditierModus(neuerEditierModus: bool)
		}
	}
}
/'
 Wiki --* WikiSeite

 SchwierigkeitsgradEnum -- IUebungsszenario 
 Aufzeichnung -- IUebungsszenario
 Uebertragungskanal  -- IUebungsszenario
 KanalEnum --> Uebertragungskanal 
 IUebungsszenario ..> IVariante
 IUebungsszenario -- Rolle 
 
 UebungsszeanrioNetzwerkBeitrittInfo -- NetzwerkClient
 UebungsszeanrioNetzwerkBeitrittInfo --NetzwerkHost
 NetzwerkClient -- UebungsszenarioNetzwerk
 NetzwerkHost -- UebungsszenarioNetzwerk
 

 Information -- InformationsEnum
 Handlungsschritt -- Information
 Information -- RolleEnum

 OperationsEnum -- Handlungsschritt
 Operationen -- Handlungsschritt

 Handlungsschritt -- Rolle 
 Rolle --> RolleEnum
 '/

 

 IVariante <.. IUebungsszenario

 
 Rolle <-- IUebungsszenario

 InformationsEnum <-- Information
 
 Information <-- Handlungsschritt
 
 OperationsEnum <-- Handlungsschritt
 
 Handlungsschritt <-- Rolle
 
 Uebertragungskanal <-- IUebungsszenario
 KanalEnum <-- Uebertragungskanal 
 
 SchwierigkeitsgradEnum <-- IUebungsszenario
 
 Aufzeichnung <-- IUebungsszenario
 
 RolleEnum <-- Rolle
 Information --> RolleEnum
 
 Operationen <-- Handlungsschritt

WikiSeite *-- Wiki

UebungsszeanrioNetzwerkBeitrittInfo <-- NetzwerkClient
 UebungsszeanrioNetzwerkBeitrittInfo <-- NetzwerkHost
 NetzwerkClient --> UebungsszenarioNetzwerk
 NetzwerkHost --> UebungsszenarioNetzwerk
 

@enduml