@startuml name

skinparam pageMargin 10
skinparam pageExternalColor gray
skinparam pageBorderColor black


class App
{
	- navigator : Navigator
	- MainWindow : MainView
}

package Commands
{
	class DelegateCommand
	{
		+ CanExecuteChanged : event Eventhandler
		+ execute : Action<object>
		+ canExecute : Predicate<object>?
		+ DelegateCommand()
		+ CanExecute() : bool
		+ Execute(): void
		+ RaiseCanExecuteChanged(): void
	}
}

/'************************************************************'/
/'PACKAGE UI												  '/
/'************************************************************'/
package UI
{
	together{
		class MainView
		{
		}

		class MainViewModel
		{
			- _navigator : Navigator
			<< get, >> AktuellesViewModel : BaseViewModel
			+ MainViewModel(Navigator)
			- aktuellesViewModelGeaendert() : void
		}

		class Navigator
		{
			+ aktuellesViewModelGeaendert : event Action
			- _aktuellesviewModel : BaseViewModel
			+ aktuellesViewModel() : BaseViewModel
			<< get, set >> aktuellesViewModel() : BaseViewModel
			- ViewModelWurdeGeändert() : void
		}

		class BaseViewModel
		{
			+ PropertyChanged : event
			+ BaseViewModel() : void
			+ PropertyChangedEventHandler() : event
			# OnPropertyChanged() : void
			# RaisedPropertyChanged() : void
		}
	}

	together{
		class LobbyErstellenViewModel
		{
			+ lobbyname: string 
			+ ausgProtokoll: int 
			+ ausgSchwierigkeit: int 
			+ ausgVariante: int 
			+ ausgPhaseStart: int 
			+ ausgPhaseEnde: int 
			+ netzwerkbasiert: bool 
			+ LobbyErstellenViewModel() : void
			+ LobbyErstellen() : void
			# LobbyErstellenCommand() : void
			# ZurueckZumHauptmenueCommand() : void
		}

		class LobbyErstellenView
		{
		}
	}
	
	together{
		class LobbyBeitretenViewModel
		{
			+ verfuegbareLobbys : ObservableCollection 
			+ ausgewaehlteLobby : int 
			+ LobbyBeitretenViewModel() : void 
			+ SpielBeitreten() : void 
			# SpielBeitretenCommand() : void 
			# ZurueckZumHauptmenueCommand() : void 
		}

		class LobbyBeitretenView
		{
		}
	}
	
	together{
		class HauptMenueViewModel
		{
			+ HauptMenueViewModel() : void
			# LobbyErstellenCommand(): void
			# LobbyBeitretenCommand(): void
			# WikiOeffnenCommand(): void
		}
			
		class HauptMenueView
		{
		}
	}
	
	together{
		class LobbyViewModel
		{
			+ NameLobby : string
			+ Variante : string
			+ Schwierigkeitsgrad : string
			+ Phase : string
			+ Protokoll : string
			+ AliasAliceText : string
			+ AliasBobText : string
			+ AliasEveText : string
			+ PasswortAliceText : string
			+ PasswortBobText : string
			+ PasswortEveText : string
			+ BenutzerRollenCollection : ObservableCollection()
			+ LobbyViewModel() : void
			+ SpielStarten() : void
			# SpielStartenCommand() : void
			# LobbyVerlassenCommand() : void
			# ButtonBestaetigenCommand() : void
			# ButtonHauptmenueCommand() : void
			# ButtonWikiCommand() : void
		}

		class LobbyView
		{
		}
	}
	
	together{
		class WikiViewModel
		{
			+ WikiSeiten : ObservableCollection<WikiSeite>
			+ SelektierteWikiSeite : WikiSeite
			- editierModus : bool
			+ <<get, set>> EditierModus : bool
			+ LabelSichtbar : Visibility
			+ TextBoxSichtbar : Visibility
			+ SeitenErweitern : DelegateCommand
			+ SeitenBearbeiten : DelegateCommand
			+ SeiteEntfernen : DelegateCommand
			+ SeiteSelektiert : DelegateCommand
			+ WikiViewModel() : void

			# UmbenennenCommand() : void
			# WikiVerlassenCommand() : void
			# ZumHauptmenueCommand() : void
		}

		class WikiView
		{
		}
	}
	

	together{
		class AufzeichnungViewModel
		{
			+ Aufzeichnung : List
			+ AufzeichnungViewModel() : void
			# ZumHauptmenueCommand() : void
		}

		class AufzeichnungView
		{
		}
	}

	together{
		class SpielViewModel
		{
			# BitfolgeErzeugenCommand() : void /'Bitzahlen Icon'/
			# Ver_EntschluesselnCommand() : void /'Schluessel Icon'/
			# PhotonenErzeugenCommand() : void /'P Icon'/
			# PolschaErzeugenCommand() : void /'Filter Icon'/
			# StreichenCommand() : void /'Radiergummi Icon'/
			# TextEditierenCommand() : void /'Editieren Icon'/
			# VergleichenCommand() : void /'Waage Icon'/
			# ZahlErzeugenCommand() : void /'Raute Icon'/
			# ZufaelligGenerierenCommand() : void /'Wuerfel Icon'/
			# FragezeichenCommand() : void /'Fragezeichen Icon'/
			# ZugBeendenCommand() : void
			# HauptmenueCommand() : void
			# OperationAusfuhrenCommand() : void
			# InformationLoeschenCommand() : void
		}
		
		class SpielView
		{
		}

		note right of SpielViewModel
		Bitzahlen Icon : BitfolgeErzeugenCommand()
		Schluessel Icon : Ver_EntschluesselnCommand()
		P Icon : PhotonenErzeugenCommand()
		Filter Icon : PolschaErzeugenCommand()
		Radiergummi Icon : StreichenCommand()
		Editieren Icon : TextEditierenCommand()
		Waage Icon : VergleichenCommand()
		Raute Icon : ZahlErzeugenCommand()
		Wuerfel Icon : ZufaelligGenerierenCommand()
		Fragezeichen Icon : FragezeichenCommand()
		end note
	}

	together{
		class SpielEveViewModel
		{
			# BitfolgeErzeugenCommand() : void /'Bitzahlen Icon'/
			# Ver_EntschluesselnCommand() : void /'Schluessel Icon'/
			# PhotonenErzeugenCommand() : void /'P Icon'/
			# PolschaErzeugenCommand() : void /'Filter Icon'/
			# StreichenCommand() : void /'Radiergummi Icon'/
			# TextEditierenCommand() : void /'Editieren Icon'/
			# VergleichenCommand() : void /'Waage Icon'/
			# ZahlErzeugenCommand() : void /'Raute Icon'/
			# ZufaelligGenerierenCommand() : void /'Wuerfel Icon'/
			# FragezeichenCommand() : void /'Fragezeichen Icon'/
			# ZugBeendenCommand() : void
			# HauptmenueCommand() : void
			# OperationAusfuhrenCommand() : void
			# InformationLoeschenCommand() : void
		}

		class SpielEveView
		{
		}

		note left of SpielEveViewModel
		Bitzahlen Icon : BitfolgeErzeugenCommand() : void
		Schluessel Icon : Ver_EntschluesselnCommand() : void
		P Icon : PhotonenErzeugenCommand() : void
		Filter Icon : PolschaErzeugenCommand() : void
		Radiergummi Icon : StreichenCommand() : void
		Editieren Icon : TextEditierenCommand() : void
		Waage Icon : VergleichenCommand() : void
		Raute Icon : ZahlErzeugenCommand() : void
		Wuerfel Icon : ZufaelligGenerierenCommand() : void
		Fragezeichen Icon : FragezeichenCommand() : void
		end note
	}
	
	together{
		class RolleEntsperrenViewModel
		{
			- passwort : string
			# RolleEntsperrenCommand() : void 
			# ZumHauptmenueCommand() : void
		}

		class RolleEntsperrenView
		{
		}
	}

	
}
App -- MainView
App -- Navigator
MainView -- MainViewModel
BaseViewModel <|-u- RolleEntsperrenViewModel
BaseViewModel <|-u- AufzeichnungViewModel
BaseViewModel <|-u- SpielEveViewModel
BaseViewModel <|-u- SpielViewModel
BaseViewModel <|-u- LobbyBeitretenViewModel
BaseViewModel <|-u- LobbyViewModel
BaseViewModel <|-- WikiViewModel
BaseViewModel <|-- HauptMenueViewModel
BaseViewModel <|-- LobbyErstellenViewModel
BaseViewModel <|-- MainViewModel
Navigator -- MainViewModel
SpielView -- SpielViewModel
SpielEveView -- SpielEveViewModel
RolleEntsperrenView -- RolleEntsperrenViewModel
LobbyErstellenView -- LobbyErstellenViewModel
LobbyBeitretenView -- LobbyBeitretenViewModel
AufzeichnungView -- AufzeichnungViewModel
HauptMenueView -- HauptMenueViewModel
LobbyView -- LobbyViewModel
WikiView -- WikiViewModel

@enduml