@startuml name

skinparam pageMargin 10
skinparam pageExternalColor gray
skinparam pageBorderColor black

/'************************************************************'/
/'PACKAGE UI												  '/
/'************************************************************'/
package UI
{
	class MainViewModel
	{
		+ MainViewModel(Navigator)
		+ CurrentViewModel : BaseViewModel
		- OnCurrentViewModelChanged() : void
	}

	class Navigator
	{
		+ CurrentViewModel() : BaseViewModel
		+ CurrentViewModelChanged() : Event Action
		- OnCurrentViewModelChanged() : void
	}

	class LobbyErstellenViewModel
	{
		 + lobbyname: string 
		 + ausgProtokoll: int 
		 + ausgSchwierigkeit: int 
		 + ausgVariante: int 
		 + ausgPhaseStart: int 
		 + ausgPhaseEnde: int 
		 + netzwerkbasiert: bool 
		 + LobbyErstellenViewModel() : void
		 + LobbyErstellen() : void
		 # LobbyErstellenCommand() : void
		 # ZurueckZumHauptmenueCommand() : void
	}
	
	class LobbyBeitretenViewModel
	{
		 + verfuegbareLobbys : ObservableCollection 
		 + ausgewaehlteLobby : int 
		 + LobbyBeitretenViewModel() : void 
		 + SpielBeitreten() : void 
		 # SpielBeitretenCommand() : void 
		 # ZurueckZumHauptmenueCommand() : void 
	}
	
	class HauptMenueViewModel
	{
		 + HauptMenueViewModel() : void
		 # LobbyErstellenCommand(): void
		 # LobbyBeitretenCommand(): void
		 # WikiOeffnenCommand(): void
	}
	
	class LobbyViewModel
	{
		 + NameLobby : string
		 + Variante : string
		 + Schwierigkeitsgrad : string
		 + Phase : string
		 + Protokoll : string
		 + AliasAliceText : string
		 + AliasBobText : string
		 + AliasEveText : string
		 + PasswortAliceText : string
		 + PasswortBobText : string
		 + PasswortEveText : string
		 + BenutzerRollenCollection : ObservableCollection()
		 + LobbyViewModel() : void
		 + SpielStarten() : void
		 # SpielStartenCommand() : void
		 # LobbyVerlassenCommand() : void
		 # ButtonBestaetigenCommand() : void
		 # ButtonHauptmenueCommand() : void
		 # ButtonWikiCommand() : void
	}
	
	class WikiViewModel
	{
		 + eintraege : ObservableCollection
		 + eintragsIndex : int
		 + WikiViewModel() : void
		 # UmbenennenCommand() : void
		 # HinzufuegenCommand() : void
		 # LoeschenCommand() : void
		 # SpeichernCommand() : void
		 # WikiVerlassenCommand() : void
		 # ZumHauptmenueCommand() : void
	}
	
	class BaseViewModel
	{
		 + PropertyChanged : event
		 + BaseViewModel() : void
		 + PropertyChangedEventHandler() : event
		 # OnPropertyChanged() : void
		 # RaisedPropertyChanged() : void
	}

	class AufzeichnungViewModel
	{
		+ Aufzeichnung : List
		+ AufzeichnungViewModel() : void
		# ZumHauptmenueCommand() : void
	}

	class SpielViewModel
	{
	}

	class SpielEveViewModel
	{
	}

	class SpielEveView
	{
	}

	class SpielView
	{
	}

	class AufzeichnungView
	{
	}

	class LobbyErstellenView
	{
	}
	
	class LobbyBeitretenView
	{
	}
	
	class HauptMenueView
	{
	}
	
	class LobbyView
	{
	}
	
	class WikiView
	{
	}
}

BaseViewModel <|-- LobbyBeitretenViewModel
BaseViewModel <|-- LobbyViewModel
BaseViewModel <|-- WikiViewModel
BaseViewModel <|-- HauptMenueViewModel
BaseViewModel <|-- LobbyErstellenViewModel
BaseViewModel <|-- MainViewModel
LobbyErstellenView -- LobbyErstellenViewModel
LobbyBeitretenView -- LobbyBeitretenViewModel
HauptMenueView -- HauptMenueViewModel
LobbyView -- LobbyViewModel
WikiView -- WikiViewModel

@enduml